[robot_info]

NUM_OF_JOINTS = 6

JOINT0_GEAR_OFFSET = 0
JOINT1_GEAR_OFFSET = 0
JOINT2_GEAR_OFFSET = 0
JOINT3_GEAR_OFFSET = 0
JOINT4_GEAR_OFFSET = 0
JOINT5_GEAR_OFFSET = 0

JOINT0_COUNT_PER_ROTATION = 524288
JOINT1_COUNT_PER_ROTATION = 524288
JOINT2_COUNT_PER_ROTATION = 524288
JOINT3_COUNT_PER_ROTATION = 524288
JOINT4_COUNT_PER_ROTATION = 524288
JOINT5_COUNT_PER_ROTATION = 524288

JOINT0_GEAR_REDUCTION_RATIO = 121
JOINT1_GEAR_REDUCTION_RATIO = 121
JOINT2_GEAR_REDUCTION_RATIO = 101
JOINT3_GEAR_REDUCTION_RATIO = 101
JOINT4_GEAR_REDUCTION_RATIO = 101
JOINT5_GEAR_REDUCTION_RATIO = 101

; DH_ALPHA_PARAM_DEGREE
; pi/2 0.0 0.0 pi/2 -pi/2 0.0
JOINT0_DH_ALPHA_PARAM_DEGREE = 90
JOINT1_DH_ALPHA_PARAM_DEGREE = 0
JOINT2_DH_ALPHA_PARAM_DEGREE = 90
JOINT3_DH_ALPHA_PARAM_DEGREE = -90
JOINT4_DH_ALPHA_PARAM_DEGREE = 90
JOINT5_DH_ALPHA_PARAM_DEGREE = 0

; DH_A_MICROMETER
JOINT0_DH_A_PARAM_MICROMETER = 75000
JOINT1_DH_A_PARAM_MICROMETER = 280000
JOINT2_DH_A_PARAM_MICROMETER = 0
JOINT3_DH_A_PARAM_MICROMETER = 0
JOINT4_DH_A_PARAM_MICROMETER = 0
JOINT5_DH_A_PARAM_MICROMETER = 0

; DH_D_MICROMETER
JOINT0_DH_D_PARAM_MICROMETER = 118600
JOINT1_DH_D_PARAM_MICROMETER = 0
JOINT2_DH_D_PARAM_MICROMETER = 0
JOINT3_DH_D_PARAM_MICROMETER = 270000
JOINT4_DH_D_PARAM_MICROMETER = 0
JOINT5_DH_D_PARAM_MICROMETER = 170000

; DH_THETA_MICROMETER
JOINT0_DH_THETA_PARAM_MICROMETER = 0
JOINT1_DH_THETA_PARAM_MICROMETER = 0
JOINT2_DH_THETA_PARAM_MICROMETER = 0
JOINT3_DH_THETA_PARAM_MICROMETER = 0
JOINT4_DH_THETA_PARAM_MICROMETER = 0
JOINT5_DH_THETA_PARAM_MICROMETER = 0

; only use -1 or 1
JOINT0_INVERSE_FACTOR = -1
JOINT1_INVERSE_FACTOR = -1
JOINT2_INVERSE_FACTOR =	1
JOINT3_INVERSE_FACTOR = -1
JOINT4_INVERSE_FACTOR = -1
JOINT5_INVERSE_FACTOR = -1

JOINT0_HOME_OFFSET = 0
JOINT1_HOME_OFFSET = 90
JOINT2_HOME_OFFSET = 90
JOINT3_HOME_OFFSET = 0
JOINT4_HOME_OFFSET = 0
JOINT5_HOME_OFFSET = 0


[robot_threshold]

TCP_SPEED_MAX_TH = 1500
TCP_ACCELERATION_MAX_TH = 4000

JOINT0_POSITION_RANGE_MIN_TH = -360
JOINT1_POSITION_RANGE_MIN_TH = -100
JOINT2_POSITION_RANGE_MIN_TH = -70
JOINT3_POSITION_RANGE_MIN_TH = -360
JOINT4_POSITION_RANGE_MIN_TH = -120
JOINT5_POSITION_RANGE_MIN_TH = -360

JOINT0_POSITION_RANGE_MAX_TH = 360
JOINT1_POSITION_RANGE_MAX_TH = 220
JOINT2_POSITION_RANGE_MAX_TH = 230
JOINT3_POSITION_RANGE_MAX_TH = 360
JOINT4_POSITION_RANGE_MAX_TH = 120
JOINT5_POSITION_RANGE_MAX_TH = 360

JOINT0_VELOCITY_RANGE_MAX_TH = 75
JOINT1_VELOCITY_RANGE_MAX_TH = 75
JOINT2_VELOCITY_RANGE_MAX_TH = 90
JOINT3_VELOCITY_RANGE_MAX_TH = 90
JOINT4_VELOCITY_RANGE_MAX_TH = 90
JOINT5_VELOCITY_RANGE_MAX_TH = 90

JOINT0_TCP_ACCELERATION_RANGE_MAX_TH = 20000
JOINT1_TCP_ACCELERATION_RANGE_MAX_TH = 20000
JOINT2_TCP_ACCELERATION_RANGE_MAX_TH = 20000
JOINT3_TCP_ACCELERATION_RANGE_MAX_TH = 20000
JOINT4_TCP_ACCELERATION_RANGE_MAX_TH = 20000
JOINT5_TCP_ACCELERATION_RANGE_MAX_TH = 20000

JOINT0_JOINT_ACCELERATION_RANGE_MAX_TH = 150
JOINT1_JOINT_ACCELERATION_RANGE_MAX_TH = 150
JOINT2_JOINT_ACCELERATION_RANGE_MAX_TH = 180
JOINT3_JOINT_ACCELERATION_RANGE_MAX_TH = 180
JOINT4_JOINT_ACCELERATION_RANGE_MAX_TH = 180
JOINT5_JOINT_ACCELERATION_RANGE_MAX_TH = 180

JOINT0_TORQUE_RANGE_MAX_TH = 0
JOINT1_TORQUE_RANGE_MAX_TH = 0
JOINT2_TORQUE_RANGE_MAX_TH = 0
JOINT3_TORQUE_RANGE_MAX_TH = 0
JOINT4_TORQUE_RANGE_MAX_TH = 0
JOINT5_TORQUE_RANGE_MAX_TH = 0

JOINT0_POSITION_FOLLOW_TH = 24
JOINT1_POSITION_FOLLOW_TH = 24
JOINT2_POSITION_FOLLOW_TH = 24
JOINT3_POSITION_FOLLOW_TH = 24
JOINT4_POSITION_FOLLOW_TH = 24
JOINT5_POSITION_FOLLOW_TH = 24

JOINT0_VELOCITY_FOLLOW_STOP_TH = 24
JOINT1_VELOCITY_FOLLOW_STOP_TH = 24
JOINT2_VELOCITY_FOLLOW_STOP_TH = 24
JOINT3_VELOCITY_FOLLOW_STOP_TH = 24
JOINT4_VELOCITY_FOLLOW_STOP_TH = 24
JOINT5_VELOCITY_FOLLOW_STOP_TH = 24

[safety_module_threshold]

;JOINT_SPEED_UNLIMITED FALSE:0, TRUE:1
JOINT_SPEED_UNLIMITED = 0
JOINT_VELOCITY_FOLLOW_PERCENT_THRESHOLD = 10
TCP_POSITION_THRESHOLD = 300

JOINT0_BRAKE_MONITOR_TH = 5
JOINT1_BRAKE_MONITOR_TH = 5
JOINT2_BRAKE_MONITOR_TH = 5
JOINT3_BRAKE_MONITOR_TH = 5
JOINT4_BRAKE_MONITOR_TH = 5
JOINT5_BRAKE_MONITOR_TH = 5

JOINT0_COL_DET_TORQ_LIMIT = 0
JOINT1_COL_DET_TORQ_LIMIT = 0
JOINT2_COL_DET_TORQ_LIMIT = 0
JOINT3_COL_DET_TORQ_LIMIT = 0
JOINT4_COL_DET_TORQ_LIMIT = 0
JOINT5_COL_DET_TORQ_LIMIT = 0

JOINT0_COL_DET_ACCEL_ZERO_RANGE = 0
JOINT1_COL_DET_ACCEL_ZERO_RANGE = 0
JOINT2_COL_DET_ACCEL_ZERO_RANGE = 0
JOINT3_COL_DET_ACCEL_ZERO_RANGE = 0
JOINT4_COL_DET_ACCEL_ZERO_RANGE = 0
JOINT5_COL_DET_ACCEL_ZERO_RANGE = 0